return {
  [0] = {
    map_data_path = "levels.level0_level",
    deco_data_path = "levels.level0_decoration",
    enemy_data_path = "levels.level1_enemies",
    tileset_path = "./assets/graphics/tilesets/level0.png",
    deco_tileset_path = "./assets/graphics/tilesets/level1_decoration.png",
    background_index = 13,
    start_pos = { x = 32 * 0, y = 32 * 6 },
    portal_pos = { x = 32 * 29, y = 32 * 7 },
  },
  [1] = {
    map_data_path = "levels.level1_level",
    deco_data_path = "levels.level1_decoration",
    enemy_data_path = "levels.level1_enemies",
    tileset_path = "./assets/graphics/tilesets/level1.png",
    deco_tileset_path = "./assets/graphics/tilesets/level1_decoration.png",
    background_index = 2,
    start_pos = { x = 32 * 0, y = 32 * 7 },
    portal_pos = { x = 32 * 59, y = 32 * 25 },
  },
  [2] = {
    map_data_path = "levels.level2_level",
    deco_data_path = "levels.level2_decoration",
    enemy_data_path = "levels.level0_decoration",
    tileset_path = "./assets/graphics/tilesets/level2.png",
    deco_tileset_path = "./assets/graphics/tilesets/level2_decoration.png",
    background_index = 3,
    start_pos = { x = 32 * 0, y = 32 * 7 },
    portal_pos = { x = 32 * 59, y = 32 * 25 },
  },
  [3] = {
    map_data_path = "levels.level3_level",
    deco_data_path = "levels.level3_decoration",
    enemy_data_path = "levels.level0_decoration",
    tileset_path = "./assets/graphics/tilesets/level3.png",
    deco_tileset_path = "./assets/graphics/tilesets/level3_decoration.png",
    background_index = 4,
    start_pos = { x = 32 * 0, y = 32 * 7 },
    portal_pos = { x = 32 * 59, y = 32 * 25 },
  },
  [4] = {
    map_data_path = "levels.level4_level",
    deco_data_path = "levels.level4_decoration",
    enemy_data_path = "levels.level0_decoration",
    tileset_path = "./assets/graphics/tilesets/level4.png",
    deco_tileset_path = "./assets/graphics/tilesets/level4_decoration.png",
    background_index = 5,
    start_pos = { x = 32 * 0, y = 32 * 7 },
    portal_pos = { x = 32 * 59, y = 32 * 25 },
  },
  [5] = {
    map_data_path = "levels.level5_level",
    deco_data_path = "levels.level5_decoration",
    enemy_data_path = "levels.level0_decoration",
    tileset_path = "./assets/graphics/tilesets/level5.png",
    deco_tileset_path = "./assets/graphics/tilesets/level5_decoration.png",
    background_index = 6,
    start_pos = { x = 32 * 0, y = 32 * 7 },
    portal_pos = { x = 32 * 59, y = 32 * 25 },
  },
  [6] = {
    map_data_path = "levels.level6_level",
    deco_data_path = "levels.level6_decoration",
    enemy_data_path = "levels.level0_decoration",
    tileset_path = "./assets/graphics/tilesets/level6.png",
    deco_tileset_path = "./assets/graphics/tilesets/level6_decoration.png",
    background_index = 7,
    start_pos = { x = 32 * 0, y = 32 * 7 },
    portal_pos = { x = 32 * 59, y = 32 * 25 },
  },
  [7] = {
    map_data_path = "levels.level7_level",
    deco_data_path = "levels.level7_decoration",
    enemy_data_path = "levels.level0_decoration",
    tileset_path = "./assets/graphics/tilesets/level7.png",
    deco_tileset_path = "./assets/graphics/tilesets/level7_decoration.png",
    background_index = 8,
    start_pos = { x = 32 * 0, y = 32 * 7 },
    portal_pos = { x = 32 * 59, y = 32 * 25 },
  },
  [8] = {
    map_data_path = "levels.level8_level",
    deco_data_path = "levels.level8_decoration",
    enemy_data_path = "levels.level0_decoration",
    tileset_path = "./assets/graphics/tilesets/level8.png",
    deco_tileset_path = "./assets/graphics/tilesets/level8_decoration.png",
    background_index = 9,
    start_pos = { x = 32 * 0, y = 32 * 7 },
    portal_pos = { x = 32 * 59, y = 32 * 25 },
  },
  [9] = {
    map_data_path = "levels.level9_level",
    deco_data_path = "levels.level9_decoration",
    enemy_data_path = "levels.level1_enemies",
    tileset_path = "./assets/graphics/tilesets/level9.png",
    deco_tileset_path = "./assets/graphics/tilesets/level9_decoration.png",
    background_index = 10,
    start_pos = { x = 32 * 0, y = 32 * 20 },
    portal_pos = { x = 32 * 59, y = 32 * 25 },
  },
  [10] = {
    map_data_path = "levels.level10_level",
    deco_data_path = "levels.level10_decoration",
    enemy_data_path = "levels.level0_decoration",
    tileset_path = "./assets/graphics/tilesets/level10.png",
    deco_tileset_path = "./assets/graphics/tilesets/level10_decoration.png",
    background_index = 11,
    start_pos = { x = 32 * 0, y = 32 * 20 },
    portal_pos = { x = 32 * 59, y = 32 * 23 },
  },
  [11] = {
    map_data_path = "levels.level11_level",
    deco_data_path = "levels.level11_decoration",
    tileset_path = "./assets/graphics/tilesets/level11.png",
    deco_tileset_path = "./assets/graphics/tilesets/level11_decoration.png",
    background_index = 12,
    start_pos = { x = 32 * 0, y = 32 * 10 },
    portal_pos = { x = 32 * 59, y = 32 * 25 },
  },
}
