return {
	[1] = {
		map_data_path = "levels.level1",
		deco_data_path = "levels.level1_decorations",
		tileset_path = "./assets/graphics/tilesets/level1.png",
		deco_tileset_path = "./assets/graphics/tilesets/grass.png",
		background_index = 2,
		start_pos = { x = 32 * 0, y = 32 * 7 },
		portal_pos = { x = 32 * 59, y = 32 * 25 },
	},
	[2] = {
		map_data_path = "levels.level2",
		deco_data_path = "levels.level2_decorations",
		tileset_path = "./assets/graphics/tilesets/level2.png",
		deco_tileset_path = "./assets/graphics/tilesets/grass.png",
		background_index = 3,
		start_pos = { x = 32 * 0, y = 32 * 7 },
		portal_pos = { x = 32 * 59, y = 32 * 25 },
	},
	[3] = {
		map_data_path = "levels.level3",
		deco_data_path = "levels.level3_decorations",
		tileset_path = "./assets/graphics/tilesets/level3.png",
		deco_tileset_path = "./assets/graphics/tilesets/grass.png",
		background_index = 4,
		start_pos = { x = 32 * 0, y = 32 * 7 },
		portal_pos = { x = 32 * 59, y = 32 * 25 },
	},
	[4] = {
		map_data_path = "levels.level4",
		deco_data_path = "levels.level4_decorations",
		tileset_path = "./assets/graphics/tilesets/level4.png",
		deco_tileset_path = "./assets/graphics/tilesets/grass.png",
		background_index = 5,
		start_pos = { x = 32 * 0, y = 32 * 7 },
		portal_pos = { x = 32 * 59, y = 32 * 25 },
	},
	[5] = {
		map_data_path = "levels.level5",
		deco_data_path = "levels.level5_decorations",
		tileset_path = "./assets/graphics/tilesets/level5.png", deco_tileset_path = "./assets/graphics/tilesets/grass.png",
		background_index = 6,
		start_pos = { x = 32 * 0, y = 32 * 7 },
		portal_pos = { x = 32 * 59, y = 32 * 25 },
	},
}
